# Generated by Django 5.0.6 on 2025-09-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_comment_page_sitestat_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comment_videos/'),
        ),
    ]
