# Generated by Django 5.0.6 on 2025-10-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestat',
            options={'verbose_name': '页面统计', 'verbose_name_plural': '页面统计'},
        ),
    ]
