# Generated by Django 5.0.6 on 2025-10-27 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_sitestat_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL标识符', max_length=100, unique=True)),
                ('title', models.CharField(help_text='旅行标题', max_length=200)),
                ('description', models.TextField(blank=True, help_text='简介描述')),
                ('icon', models.CharField(default='🗺️', help_text='旅行图标', max_length=10)),
                ('start_date', models.DateField(blank=True, help_text='开始日期', null=True)),
                ('end_date', models.DateField(blank=True, help_text='结束日期', null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', help_text='状态', max_length=20)),
                ('visibility', models.CharField(choices=[('private', '私有'), ('public', '公开')], default='private', help_text='可见性', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='模块配置')),
                ('overview', models.JSONField(blank=True, default=dict, help_text='行程内容')),
                ('theme_color', models.CharField(default='#f0e68c', help_text='主题颜色', max_length=20)),
                ('background_music', models.CharField(blank=True, help_text='背景音乐URL', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '旅行计划',
                'verbose_name_plural': '旅行计划',
                'ordering': ['-created_at'],
            },
        ),
    ]
