# Generated by Django 5.0.6 on 2025-10-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestat',
            options={'ordering': ['id'], 'verbose_name': '页面统计', 'verbose_name_plural': '页面统计'},
        ),
        migrations.AddField(
            model_name='sitestat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
