# Generated by Django 5.0.6 on 2025-10-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_sitestat_options_sitestat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='个人简介', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('novice', '新手'), ('explorer', '探索者'), ('wanderer', '漫游者'), ('adventurer', '冒险家'), ('master', '旅行大师')], default='novice', help_text='用户等级', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.CharField(blank=True, help_text='用户标签，逗号分隔', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_countries',
            field=models.CharField(blank=True, help_text='访问过的国家', max_length=200),
        ),
    ]
