# Generated by Django 5.0.6 on 2025-10-28 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_userprofile_bio_userprofile_level_userprofile_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.trip'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.CharField(blank=True, default='trip', max_length=16, null=True),
        ),
    ]
