# Generated by Django 5.0.6 on 2025-10-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_comment_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邮箱验证时间'),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱地址')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('verification_type', models.CharField(choices=[('register', '注册验证'), ('login', '登录验证'), ('reset_password', '重置密码'), ('bind_email', '绑定邮箱')], max_length=20, verbose_name='验证类型')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'email_verification_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code', 'is_used'], name='email_verif_email_6b4e7b_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_c1cad4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('qq', 'QQ'), ('wechat', '微信'), ('github', 'GitHub')], max_length=20, verbose_name='登录提供商')),
                ('uid', models.CharField(db_index=True, max_length=100, verbose_name='第三方用户ID')),
                ('unionid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UnionID（QQ/微信）')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='第三方昵称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='第三方头像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '第三方账号绑定',
                'verbose_name_plural': '第三方账号绑定',
                'db_table': 'social_account',
                'indexes': [models.Index(fields=['provider', 'uid'], name='social_acco_provide_564139_idx'), models.Index(fields=['user', 'provider'], name='social_acco_user_id_a4d1ff_idx')],
                'unique_together': {('provider', 'uid')},
            },
        ),
    ]
