# Generated by Django 5.0.6 on 2025-11-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.URLField(blank=True, help_text='图片URL（存储在腾讯云COS）', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.URLField(blank=True, help_text='视频URL（存储在腾讯云COS）', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='用户头像URL（存储在腾讯云COS）', max_length=500, null=True),
        ),
    ]
