# Generated by Django 5.0.6 on 2025-11-08 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='必填，例如：参观故宫', max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(blank=True, help_text='选填，添加更多细节', verbose_name='事件描述')),
                ('event_time', models.DateTimeField(blank=True, help_text='选填，事件发生的时间', null=True, verbose_name='事件时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('location_name', models.CharField(blank=True, help_text='例如：故宫博物院', max_length=200, verbose_name='地点名称')),
                ('location_address', models.CharField(blank=True, help_text='例如：北京市东城区景山前街4号', max_length=500, verbose_name='详细地址')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, help_text='地理坐标纬度', max_digits=10, null=True, verbose_name='纬度')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, help_text='地理坐标经度', max_digits=10, null=True, verbose_name='经度')),
                ('reminder_enabled', models.BooleanField(default=False, help_text='是否启用提醒功能', verbose_name='启用提醒')),
                ('reminder_time', models.DateTimeField(blank=True, help_text='提醒的具体时间', null=True, verbose_name='提醒时间')),
                ('reminder_method', models.CharField(choices=[('email', '邮件提醒'), ('system', '系统通知')], default='email', max_length=20, verbose_name='提醒方式')),
                ('source_app', models.CharField(choices=[('roamio', 'Roamio'), ('ralendar', 'Ralendar'), ('rote', 'Rote'), ('local_migration', '本地迁移')], default='roamio', help_text='标记事件来源于哪个应用', max_length=50, verbose_name='来源应用')),
                ('source_id', models.CharField(blank=True, help_text='原应用中的事件ID', max_length=100, verbose_name='来源ID')),
                ('synced_to_ralendar', models.BooleanField(default=False, help_text='是否已同步到 Ralendar 日历系统', verbose_name='已同步到Ralendar')),
                ('ralendar_event_id', models.IntegerField(blank=True, help_text='在 Ralendar 中的事件ID', null=True, verbose_name='Ralendar事件ID')),
                ('is_completed', models.BooleanField(default=False, help_text='事件是否已完成', verbose_name='已完成')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='已删除')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.trip', verbose_name='关联旅行')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_events', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '旅行事件',
                'verbose_name_plural': '旅行事件',
                'db_table': 'trips_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trip', 'user'], name='idx_trip_user'), models.Index(fields=['event_time'], name='idx_event_time'), models.Index(fields=['ralendar_event_id'], name='idx_ralendar_id'), models.Index(fields=['is_deleted'], name='idx_is_deleted')],
            },
        ),
    ]

