# Generated by Django 5.2.10 on 2026-05-04 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_tripevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ralendar_event_ids',
            field=models.JSONField(blank=True, default=list, help_text='Ralendar 事件 IDs'),
        ),
        migrations.AddField(
            model_name='trip',
            name='ralendar_synced_at',
            field=models.DateTimeField(blank=True, help_text='同步到 Ralendar 的时间', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='生日', null=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='verification_type',
            field=models.CharField(choices=[('register', '注册验证'), ('login', '登录验证'), ('reset_password', '重置密码'), ('bind_email', '绑定邮箱'), ('change_email', '更改邮箱')], max_length=20, verbose_name='验证类型'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', '普通用户'), ('vip', 'VIP 用户'), ('svip', 'SVIP 用户')], default='free', max_length=20, verbose_name='会员类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('expired', '已过期'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('trips_count', models.IntegerField(default=0, verbose_name='已创建旅行数量')),
                ('trips_created_today', models.IntegerField(default=0, verbose_name='今日已创建旅行数量')),
                ('trips_reset_date', models.DateField(default=django.utils.timezone.now, verbose_name='上次重置日期（用于每日限制）')),
                ('weekly_free_trips_remaining', models.IntegerField(default=0, verbose_name='本周剩余免费旅行次数')),
                ('weekly_reset_date', models.DateField(blank=True, null=True, verbose_name='上次周重置日期')),
                ('ai_remaining', models.IntegerField(default=2, verbose_name='剩余 AI 次数')),
                ('ai_total', models.IntegerField(default=2, verbose_name='总 AI 次数（每日重置）')),
                ('last_ai_reset_date', models.DateField(default=django.utils.timezone.now, verbose_name='上次 AI 重置日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员订阅',
                'verbose_name_plural': '会员订阅',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('subscription_type', models.CharField(choices=[('vip', 'VIP'), ('svip', 'SVIP')], max_length=20, verbose_name='订阅类型')),
                ('duration_months', models.IntegerField(default=1, verbose_name='订阅时长（月）')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('payment_method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('mock', '模拟支付')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunded', '已退款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('pingpp_charge_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ping++ Charge ID')),
                ('pingpp_order_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ping++ Order ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='订单过期时间')),
                ('callback_data', models.JSONField(blank=True, default=dict, verbose_name='支付回调数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员订阅订单',
                'verbose_name_plural': '会员订阅订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripCreationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('payment_method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('mock', '模拟支付')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunded', '已退款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('pingpp_charge_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ping++ Charge ID')),
                ('pingpp_order_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ping++ Order ID')),
                ('description', models.CharField(default='创建新旅行', max_length=200, verbose_name='订单描述')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='订单过期时间')),
                ('callback_data', models.JSONField(blank=True, default=dict, verbose_name='支付回调数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_creation_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '旅行创建订单',
                'verbose_name_plural': '旅行创建订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ralendar_user_id', models.IntegerField(help_text='Ralendar 用户 ID')),
                ('ralendar_username', models.CharField(help_text='Ralendar 用户名', max_length=100)),
                ('ralendar_email', models.EmailField(blank=True, help_text='Ralendar 邮箱', max_length=254, null=True)),
                ('ralendar_avatar', models.URLField(blank=True, help_text='Ralendar 头像 URL', null=True)),
                ('ralendar_provider', models.CharField(blank=True, help_text='Ralendar 登录方式：qq/acwing/email', max_length=20, null=True)),
                ('ralendar_unionid', models.CharField(blank=True, help_text='Ralendar 用户的 UnionID（QQ/微信）', max_length=100, null=True)),
                ('ralendar_openid', models.CharField(blank=True, help_text='Ralendar 用户的 OpenID（QQ/微信）', max_length=100, null=True)),
                ('access_token', models.TextField(help_text='Ralendar Access Token（JWT）')),
                ('refresh_token', models.TextField(blank=True, help_text='Ralendar Refresh Token（可选）', null=True)),
                ('token_type', models.CharField(default='Bearer', help_text='Token 类型', max_length=20)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token 过期时间', null=True)),
                ('scope', models.CharField(default='calendar:read calendar:write', help_text='授权的权限范围', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认账号（同步时默认使用此账号）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='绑定时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='最后同步时间', null=True)),
                ('user', models.ForeignKey(help_text='Roamio 用户', on_delete=django.db.models.deletion.CASCADE, related_name='ralendar_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ralendar 账号',
                'verbose_name_plural': 'Ralendar 账号',
                'db_table': 'ralendar_accounts',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='ralendar_ac_user_id_59d407_idx'), models.Index(fields=['user', 'is_default'], name='ralendar_ac_user_id_033abb_idx')],
                'unique_together': {('user', 'ralendar_user_id')},
            },
        ),
    ]
