[uwsgi]
chdir = /home/acs/roamio
module = roamio.wsgi:application
master = true
processes = 4
socket = 127.0.0.1:8000
vacuum = true
max-requests = 5000
harakiri = 300
post-buffering = 8192
buffer-size = 65535

